# Configuração do Sistema de Busca Híbrida Avançada
# Qdrant 1.8.0+ com Sparse + Dense Vectors

hybrid_search:
  # Configurações gerais
  enabled: true
  collection_name: "hybrid_rag_collection"
  
  # Dense vectors (embeddings semânticos)
  dense_vectors:
    enabled: true
    vector_name: "dense"
    dimension: 1536  # OpenAI text-embedding-3-small
    distance_metric: "Cosine"
    on_disk: false
    quantization:
      type: "scalar"
      quantile: 0.99
      always_ram: true
  
  # Sparse vectors (BM25-style keywords)
  sparse_vectors:
    enabled: true
    vector_name: "sparse"
    # Configuração otimizada para Qdrant 1.8.0
    modifier: "idf"  # Inverse Document Frequency
    
  # Estratégia de busca híbrida
  search_strategy:
    # Pesos para combinação de scores
    dense_weight: 0.7
    sparse_weight: 0.3
    
    # Fusion methods
    fusion_method: "rrf"  # Reciprocal Rank Fusion
    rrf_k: 60  # Parâmetro RRF
    
    # Limites de busca
    dense_limit: 50
    sparse_limit: 50
    final_limit: 20
    
    # Thresholds de relevância
    min_dense_score: 0.7
    min_sparse_score: 0.1
    
  # Configurações de indexação
  indexing:
    # CPU budget para otimização (Qdrant 1.8.0)
    optimizer_cpu_budget: 0  # Auto-detect
    
    # Configurações de performance
    hnsw_config:
      m: 16
      ef_construct: 128
      full_scan_threshold: 10000
      max_indexing_threads: 0
      
    # Configurações de sparse index
    sparse_config:
      full_scan_threshold: 1000
      on_disk: false

# Configurações de embedding providers
embedding_providers:
  dense:
    provider: "openai"
    model: "text-embedding-3-small"
    dimensions: 1536
    
  sparse:
    provider: "bm25"
    # Configurações BM25
    k1: 1.2
    b: 0.75
    epsilon: 0.25
    
# Configurações de chunking otimizadas para hybrid search
chunking:
  strategy: "semantic_with_keywords"
  chunk_size: 512
  chunk_overlap: 50
  
  # Preservar keywords importantes
  preserve_keywords: true
  keyword_extraction:
    method: "tfidf"
    max_keywords: 20
    min_keyword_freq: 2
    
# Configurações de reranking
reranking:
  enabled: true
  method: "cross_encoder"
  model: "ms-marco-MiniLM-L-6-v2"
  top_k_rerank: 10
  
# Configurações de cache para performance
cache:
  enabled: true
  dense_cache_size: 1000
  sparse_cache_size: 1000
  query_cache_ttl: 3600  # 1 hora
  
# Configurações de monitoramento
monitoring:
  track_search_performance: true
  log_query_analysis: true
  benchmark_interval: 100  # queries 